Module3 task1
htmlacademy-adaptive/1426483-mishka-24 pull request #4
Opened 2021-12-02 20:03 UTC by Elena-Vlshn

2021-12-03 19:24 UTC, andreysgra requested changes
Радует то, что концепцию критерия [Б13](https://up.htmlacademy.ru/adaptive/24/criteries#b13) вы поняли абсолютно правильно.

2021-12-03 19:24 UTC, andreysgra commented on source/less/components/contacts.less
> +  .wide;
Моя рекомендация: примеси лучше записывать со скобками `.wide()`, хотя Less позволяет писать и без скобок, если у примеси нет параметров. Без скобок это очень похоже на название класса

2021-12-03 19:24 UTC, andreysgra commented on source/less/global/variables.less
> +}
В общем-то эта примесь вам не понадобится, так как она является следствием ошибки построения контейнера, о чём писал выше.

2021-12-03 19:24 UTC, andreysgra commented on source/less/components/footer.less
> +  .wide; // добавим примесь чтобы футер расширился
Стоит убрать примесь.

2021-12-03 19:24 UTC, andreysgra commented on source/less/components/header.less
> +  .wide;
И здесь убрать примесь.

2021-12-03 19:24 UTC, andreysgra commented on source/less/components/hero.less
> +  .wide;
Примесь не нужна.

2021-12-03 19:24 UTC, andreysgra commented on source/less/components/navigation.less
> +}
Абсолютное позиционирование меню нужно только при включённом JavaScript. Всё это описано в критерии Б30. Изначально, без JS меню остаётся в потоке. А для работы с JS нужен будет отдельный класс.

2021-12-03 19:24 UTC, andreysgra commented on source/less/components/reset-list.less
> +}
Как писал выше - это кандидат на удаление. Но даже если вы решили использовать данный класс, то файл `reset-list.less` нужно убрать из папки `components`, так как `.reset-list` служебный класс. Для таких классов можно завести папку `helpers`, которая будет находиться по адресу **source/less/helpers**.

2021-12-03 19:24 UTC, andreysgra commented on source/less/components/site-list.less
> +
Лишние пустые строки - линтер будет ругать вас.

2021-12-03 19:24 UTC, andreysgra commented on source/less/components/slider.less
> +
Пустая строка.

2021-12-03 19:24 UTC, andreysgra commented on source/less/components/user-list.less
> +
Пустые строки.

2021-12-03 19:24 UTC, andreysgra commented on source/less/components/visually-hidden.less
> +
Файл **visually-hidden.less** нужно вынести из папки **components**, так как `.visually-hidden` является служебным классом.

2021-12-03 19:24 UTC, andreysgra commented on source/less/global/fonts.less
> +  src: url("../../fonts/opensansbold.woff2") format("woff2");
Пути к файлам шрифтом нужно исправить (также, как и у изображений).

2021-12-03 19:24 UTC, andreysgra commented on source/less/global/variables.less
> +.wide {
Для примесей обычно заводят отдельный файл или отдельную папку (хороший подход - под каждую примесь завести отдельный файл, особенно если примесей много).

2021-12-05 04:45 UTC, Elena-Vlshn commented on source/less/components/catalog.less
> +  left: -30px;
если я убираю общий контейнер для контента, то пропадает необходимость в свойствах width, position , left для этого блока. Свойство height заменяю на min-height или padding-bottom. В этой ситуации, есть ли смысл делать обертку над заголовком. Я попробовала оба варианта , с оберткой и без, но не могу понять чем один лучше другого.

2021-12-05 10:24 UTC, andreysgra commented on source/less/components/catalog.less
> +  left: -30px;
Есть смысл делать обёртку для заголовка, потому что нижележащий контент имеет отступы
![image](https://user-images.githubusercontent.com/17790771/144742616-3b33bf4e-2653-4178-af9c-bcad4cbf8302.png)

У блока с заголовком есть серая заливка, которая должна растягиваться на всю ширину страницы. Если не делать обёртку, то горизонтальные отступы будут обрезать фоновый цвет. Поэтому фон мы делаем у обёртки (обёртка не ограничена по ширине и не имеет отступов, следовательно растягивается на всю ширину экрана).

2021-12-06 08:32 UTC, andreysgra approved these changes

2021-12-06 08:32 UTC, andreysgra commented on source/less/components/body.less
> +  width: 100%;
В общем-то и не нужно `width: 100%`.

2021-12-06 08:32 UTC, andreysgra commented on source/less/components/order.less
> +    background-image: url("../../img/mail.svg");
Нужно исправить относительные пути к картинкам.

2021-12-06 08:32 UTC, andreysgra commented on source/less/global/global.less
> +}
У тега `body` есть класс `.body` который описан в файле **body.less** - так почему бы эти свойства не перенести туда?

2021-12-06 08:32 UTC, merged